package config
package config














































}		p.User, p.Host, p.Port, p.Database, p.SSLMode)	return fmt.Sprintf("postgres://%s:****@%s:%d/%s?sslmode=%s",func (p *PostgresDatabase) PublicConnectionString() string {// PublicConnectionString returns the connection string without password for logging}		p.User, p.Password, p.Host, p.Port, p.Database, p.SSLMode)	return fmt.Sprintf("postgres://%s:%s@%s:%d/%s?sslmode=%s",func (p *PostgresDatabase) ConnectionString() string {// ConnectionString returns the PostgreSQL connection string}	}		PingTimeout:     10,		ConnMaxIdleTime: 30,		ConnMaxLifetime: 5,		MaxIdleConns:    5,		MaxOpenConns:    25,		SSLMode:         "disable",		Password:        password,		User:            user,		Database:        database,		Port:            port,		Host:            host,	return &PostgresDatabase{func NewPostgresDatabase(host string, port int, database, user, password string) *PostgresDatabase {// NewPostgresDatabase creates a PostgresDatabase config with sensible defaults}	PingTimeout     int // in seconds	ConnMaxIdleTime int // in seconds	ConnMaxLifetime int // in minutes	MaxIdleConns    int	MaxOpenConns    int	SSLMode         string	Password        string	User            string	Database        string	Port            int	Host            stringtype PostgresDatabase struct {// PostgresDatabase configuration structure for PostgreSQL connectionsimport "fmt"