package logger
package logger



















































}	return Loggerfunc GetLogger() *slog.Logger {// GetLogger returns the default logger instance}	}		return slog.LevelInfo	default:		return slog.LevelError	case "ERROR":		return slog.LevelWarn	case "WARN":		return slog.LevelInfo	case "INFO":		return slog.LevelDebug	case "DEBUG":	switch strings.ToUpper(os.Getenv("LOG_LEVEL")) {	// Default log level is INFO, can be overridden by LOG_LEVEL env variablefunc getLogLevel() slog.Level {}	slog.SetDefault(Logger)	Logger = slog.New(handler)	}		handler = slog.NewTextHandler(os.Stdout, opts)	} else {		handler = slog.NewJSONHandler(os.Stdout, opts)	if os.Getenv("LOG_FORMAT") == "json" {	var handler slog.Handler	// Choose the format based on the env variable LOG_FORMAT	}		Level: level,	opts := &slog.HandlerOptions{	level := getLogLevel()	_ = godotenv.Load()func init() {var Logger *slog.Logger)	"github.com/joho/godotenv"	"strings"	"os"	"log/slog"import (